title: GEOG 580 - Remote Sensing Principles & Applications I Final Project
logo: /assets/img/lee-soo-hyun-iFyJfU4D2Tg-unsplash.jpg
description: Image by Photo by Lee Soo Hyun on Unsplash
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
